# Site settings
#baseurl: "/"
img: "img/"
css: "css/"
#url: "#"
permalink: "/:title/"
parse_block_html: true

title: "Return Rambling"
author: "Andy Smith"
url: "https://www.smittey.co.uk"
email: "andy@andysmith.me"

social-media:
    linkedin: smittey
    github: smittey
    stackoverflow: 1295906/smittey

sass:
    style: compressed
    sass_dir: ./assets/stylesheets