# Site settings
#baseurl: "/"
img: "img/"
css: "css/"
#url: "#"
permalink: "/:title/"
parse_block_html: true

title: "Return Rambling"
author: "Andy Smith"
url: "http://Smittey.co.uk"
email: "andy@andysmith.me"